[package]
name = "audio-stream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-fn-stream = "0.2.0"
cpal = "0.14.2"
futures = { version = "0.3.25", features = ["futures-executor"] }
futures-core = "0.3.25"
hound = "3.5.0"
itertools = "0.10.5"
next-gen = "0.1.1"
nnnoiseless = "0.5.1"
rustfft = "6.1.0"
snafu = "0.7.4"
tokio = { version = "1.24.1", features = ["full"] }
wide = "0.7.5"

[features]
default = ["error-stream"]
error-stream = []
